{"nodes":[{"pos":[783,861],"content":"The exception that is thrown when an error occurs while processing a signature","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when an error occurs while processing a signature","pos":[0,78]}]},{"pos":[1696,1815],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IdentityModel.SignatureVerificationFailedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class."},{"pos":[1828,2310],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.       The following table shows the initial property values for the new instance.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new instance to a system-supplied message that describes the error.","pos":[0,151],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error."},{"content":"This message takes into account the current system culture.","pos":[152,211]},{"content":"The following table shows the initial property values for the new instance.","pos":[218,293]},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The localized error message string.|","pos":[299,475],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The localized error message string.|"}]},{"pos":[3092,3242],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IdentityModel.SignatureVerificationFailedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class with a specified error message."},{"pos":[3255,3830],"content":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new exception using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.       The following table shows the initial property values for the new instance.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor initializes the &lt;xref:System.Exception.Message%2A&gt; property of the new exception using the <ph id=\"ph1\">`message`</ph> parameter.","pos":[0,128],"source":"This constructor initializes the <xref:System.Exception.Message%2A> property of the new exception using the `message` parameter."},{"content":"The content of <ph id=\"ph1\">`message`</ph> is intended to be understood by humans.","pos":[129,193],"source":" The content of `message` is intended to be understood by humans."},{"content":"The caller of this constructor is required to ensure that this string has been localized for the current system culture.","pos":[194,314]},{"content":"The following table shows the initial property values for the new instance.","pos":[321,396]},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|<ph id=\"ph1\">`null`</ph>.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[402,568],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|`null`.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]},{"pos":[3996,4057],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[4990,5130],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IdentityModel.SignatureVerificationFailedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class with serialized data."},{"pos":[5142,5255],"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.","pos":[0,113]}]},{"pos":[5545,5660],"content":"A <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> object that holds the serialized object data.","needQuote":true,"needEscape":true,"source":"A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object that holds the serialized object data."},{"pos":[5756,5891],"content":"A <xref:System.Runtime.Serialization.StreamingContext> object that contains the contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"A &lt;xref:System.Runtime.Serialization.StreamingContext&gt; object that contains the contextual information about the source or destination.","pos":[0,135],"source":"A <xref:System.Runtime.Serialization.StreamingContext> object that contains the contextual information about the source or destination."}]},{"pos":[6646,6871],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.IdentityModel.SignatureVerificationFailedException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with a specified error message and a reference to the inner exception that is the cause of this exception.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception."},{"pos":[6884,7465],"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.       The following table shows the initial property values for the new instance.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.       The following table shows the initial property values for the new instance.      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|","pos":[0,574],"nodes":[{"content":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the &lt;xref:System.Exception.InnerException%2A&gt; property.","pos":[0,182],"source":"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property."},{"content":"The &lt;xref:System.Exception.InnerException%2A&gt; property returns the same value that is passed into the constructor.","pos":[183,297],"source":" The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor."},{"content":"The following table shows the initial property values for the new instance.","pos":[304,379]},{"content":"|Property|Value|   |--------------|-----------|   |&lt;xref:System.Exception.InnerException%2A&gt;|The inner exception reference.|   |&lt;xref:System.Exception.Message%2A&gt;|The error message string.|","pos":[385,574],"source":"      |Property|Value|   |--------------|-----------|   |<xref:System.Exception.InnerException%2A>|The inner exception reference.|   |<xref:System.Exception.Message%2A>|The error message string.|"}]}]},{"pos":[7648,7709],"content":"The error message that explains the reason for the exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message that explains the reason for the exception.","pos":[0,61]}]},{"pos":[7774,8079],"content":"The <xref:System.Exception> that is the cause of the current exception. If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Exception&gt; that is the cause of the current exception.","pos":[0,71],"source":"The <xref:System.Exception> that is the cause of the current exception."},{"content":"If the <ph id=\"ph1\">`inner`</ph> parameter is not <bpt id=\"p1\">&lt;xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept>, the current exception is raised in a <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> block that handles the inner exception.","pos":[72,305],"source":" If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.IdentityModel.SignatureVerificationFailedException\n  id: SignatureVerificationFailedException\n  children:\n  - System.IdentityModel.SignatureVerificationFailedException.#ctor\n  - System.IdentityModel.SignatureVerificationFailedException.#ctor(System.String)\n  - System.IdentityModel.SignatureVerificationFailedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.IdentityModel.SignatureVerificationFailedException.#ctor(System.String,System.Exception)\n  langs:\n  - csharp\n  name: SignatureVerificationFailedException\n  nameWithType: SignatureVerificationFailedException\n  fullName: System.IdentityModel.SignatureVerificationFailedException\n  type: Class\n  summary: The exception that is thrown when an error occurs while processing a signature\n  syntax:\n    content: 'public class SignatureVerificationFailedException : System.IdentityModel.Tokens.SecurityTokenException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  - System.IdentityModel.Tokens.SecurityTokenException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor\n  id: '#ctor'\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  langs:\n  - csharp\n  name: SignatureVerificationFailedException()\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException()\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException()\n  type: Constructor\n  assemblies:\n  - System.IdentityModel\n  namespace: System.IdentityModel\n  summary: Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new instance to a system-supplied message that describes the error. This message takes into account the current system culture.  \\n  \\n The following table shows the initial property values for the new instance.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The localized error message string.|\"\n  syntax:\n    content: public SignatureVerificationFailedException ();\n    parameters: []\n  overload: System.IdentityModel.SignatureVerificationFailedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  langs:\n  - csharp\n  name: SignatureVerificationFailedException(String)\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException(String)\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException(String)\n  type: Constructor\n  assemblies:\n  - System.IdentityModel\n  namespace: System.IdentityModel\n  summary: Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class with a specified error message.\n  remarks: \"This constructor initializes the <xref:System.Exception.Message%2A> property of the new exception using the `message` parameter. The content of `message` is intended to be understood by humans. The caller of this constructor is required to ensure that this string has been localized for the current system culture.  \\n  \\n The following table shows the initial property values for the new instance.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|`null`.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public SignatureVerificationFailedException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n  overload: System.IdentityModel.SignatureVerificationFailedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  langs:\n  - csharp\n  name: SignatureVerificationFailedException(SerializationInfo,StreamingContext)\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException(SerializationInfo,StreamingContext)\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.IdentityModel\n  namespace: System.IdentityModel\n  summary: Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class with serialized data.\n  remarks: This constructor is called during deserialization to reconstitute the exception object transmitted over a stream.\n  syntax:\n    content: protected SignatureVerificationFailedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: A <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object that holds the serialized object data.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: A <xref:System.Runtime.Serialization.StreamingContext> object that contains the contextual information about the source or destination.\n  overload: System.IdentityModel.SignatureVerificationFailedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  langs:\n  - csharp\n  name: SignatureVerificationFailedException(String,Exception)\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException(String,Exception)\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.IdentityModel\n  namespace: System.IdentityModel\n  summary: Initializes a new instance of the <xref href=\"System.IdentityModel.SignatureVerificationFailedException\"></xref> class with a specified error message and a reference to the inner exception that is the cause of this exception.\n  remarks: \"An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <xref:System.Exception.InnerException%2A> property. The <xref:System.Exception.InnerException%2A> property returns the same value that is passed into the constructor.  \\n  \\n The following table shows the initial property values for the new instance.  \\n  \\n|Property|Value|  \\n|--------------|-----------|  \\n|<xref:System.Exception.InnerException%2A>|The inner exception reference.|  \\n|<xref:System.Exception.Message%2A>|The error message string.|\"\n  syntax:\n    content: public SignatureVerificationFailedException (string message, Exception inner);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message that explains the reason for the exception.\n    - id: inner\n      type: System.Exception\n      description: The <xref:System.Exception> that is the cause of the current exception. If the `inner` parameter is not <xref uid=\"langword_csharp_null\" name=\"null\" href=\"\"></xref>, the current exception is raised in a <xref uid=\"langword_csharp_catch\" name=\"catch\" href=\"\"></xref> block that handles the inner exception.\n  overload: System.IdentityModel.SignatureVerificationFailedException.#ctor*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.IdentityModel.Tokens.SecurityTokenException\n  isExternal: false\n  name: System.IdentityModel.Tokens.SecurityTokenException\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  isExternal: false\n  name: SignatureVerificationFailedException()\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException()\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException()\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor(System.String)\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  isExternal: false\n  name: SignatureVerificationFailedException(String)\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException(String)\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  isExternal: false\n  name: SignatureVerificationFailedException(SerializationInfo,StreamingContext)\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException(SerializationInfo,StreamingContext)\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor(System.String,System.Exception)\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  isExternal: false\n  name: SignatureVerificationFailedException(String,Exception)\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException(String,Exception)\n  fullName: System.IdentityModel.SignatureVerificationFailedException.SignatureVerificationFailedException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.IdentityModel.SignatureVerificationFailedException.#ctor*\n  parent: System.IdentityModel.SignatureVerificationFailedException\n  isExternal: false\n  name: SignatureVerificationFailedException\n  nameWithType: SignatureVerificationFailedException.SignatureVerificationFailedException\n"}