{"nodes":[{"pos":[285,471],"content":"The exception that is thrown when a failure occurs in a managed thread after the underlying operating system thread has been started, but before the thread is ready to execute user code.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception that is thrown when a failure occurs in a managed thread after the underlying operating system thread has been started, but before the thread is ready to execute user code.","pos":[0,186]}]},{"pos":[483,618],"content":"The exception returned by the <xref:System.Exception.InnerException%2A> property provides information about the reason for the failure.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception returned by the &lt;xref:System.Exception.InnerException%2A&gt; property provides information about the reason for the failure.","pos":[0,135],"source":"The exception returned by the <xref:System.Exception.InnerException%2A> property provides information about the reason for the failure."}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Threading.ThreadStartException\n  id: ThreadStartException\n  children: []\n  langs:\n  - csharp\n  name: ThreadStartException\n  nameWithType: ThreadStartException\n  fullName: System.Threading.ThreadStartException\n  type: Class\n  summary: The exception that is thrown when a failure occurs in a managed thread after the underlying operating system thread has been started, but before the thread is ready to execute user code.\n  remarks: The exception returned by the <xref:System.Exception.InnerException%2A> property provides information about the reason for the failure.\n  syntax:\n    content: 'public sealed class ThreadStartException : SystemException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  implements: []\n  inheritedMembers: []\n  platform:\n  - net462\nreferences:\n- uid: System.SystemException\n  isExternal: false\n  name: System.SystemException\n"}