{"nodes":[{"pos":[1131,1207],"content":"Describes an exception that occurred during the processing of HTTP requests.","needQuote":true,"needEscape":true,"nodes":[{"content":"Describes an exception that occurred during the processing of HTTP requests.","pos":[0,76]}]},{"pos":[1219,1452],"content":"The HttpException class is an HTTP-specific exception class that enables ASP.NET to generate exception information. For more information about throwing and handling exceptions, see [Exceptions](~/add/includes/ajax-current-ext-md.md).","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"The HttpException class is an HTTP-specific exception class that enables ASP.NET to generate exception information.","pos":[0,115]},{"content":"For more information about throwing and handling exceptions, see <bpt id=\"p1\">[</bpt>Exceptions<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.","pos":[116,233],"source":" For more information about throwing and handling exceptions, see [Exceptions](~/add/includes/ajax-current-ext-md.md)."}]},{"pos":[3106,3266],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class and creates an empty <bpt id=\"p2\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> object.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class and creates an empty <xref href=\"System.Web.HttpException\"></xref> object."},{"pos":[3279,3861],"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.","pos":[0,580],"nodes":[{"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.","pos":[0,157]},{"content":"A reference to the inner exception that caused the outer exception is available from the &lt;xref:System.Exception.InnerException%2A&gt; property of the outer exception.","pos":[164,327],"source":"       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception."},{"content":"This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.","pos":[328,511]},{"content":"For more information, see &lt;xref:System.Exception.InnerException%2A&gt;.","pos":[512,580],"source":" For more information, see <xref:System.Exception.InnerException%2A>."}]}]},{"pos":[5388,5505],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using a supplied error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using a supplied error message."},{"pos":[6425,6496],"content":"The error message displayed to the client when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message displayed to the client when the exception is thrown.","pos":[0,71]}]},{"pos":[6987,7129],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using an HTTP response status code and an error message.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an HTTP response status code and an error message."},{"pos":[7285,7362],"content":"The HTTP response status code sent to the client corresponding to this error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The HTTP response status code sent to the client corresponding to this error.","pos":[0,77]}]},{"pos":[7426,7497],"content":"The error message displayed to the client when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message displayed to the client when the exception is thrown.","pos":[0,71]}]},{"pos":[8186,8293],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class with serialized data.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class with serialized data."},{"pos":[8305,8534],"content":"The HttpException constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"The HttpException constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream.","pos":[0,134]},{"content":"For more information, see <bpt id=\"p1\">[</bpt>XML and SOAP Serialization<ept id=\"p1\">](~/add/includes/ajax-current-ext-md.md)</ept>.","pos":[135,229],"source":" For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md)."}]},{"pos":[8801,8944],"content":"The <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.","needQuote":true,"needEscape":true,"source":"The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."},{"pos":[9040,9167],"content":"The <xref:System.Runtime.Serialization.StreamingContext> that holds the contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that holds the contextual information about the source or destination.","pos":[0,127],"source":"The <xref:System.Runtime.Serialization.StreamingContext> that holds the contextual information about the source or destination."}]},{"pos":[9678,9844],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using an error message and the &lt;xref:System.Exception.InnerException*&gt; property.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an error message and the <xref:System.Exception.InnerException*> property."},{"pos":[9857,10439],"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.","pos":[0,580],"nodes":[{"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.","pos":[0,157]},{"content":"A reference to the inner exception that caused the outer exception is available from the &lt;xref:System.Exception.InnerException%2A&gt; property of the outer exception.","pos":[164,327],"source":"       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception."},{"content":"This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.","pos":[328,511]},{"content":"For more information, see &lt;xref:System.Exception.InnerException%2A&gt;.","pos":[512,580],"source":" For more information, see <xref:System.Exception.InnerException%2A>."}]}]},{"pos":[11640,11711],"content":"The error message displayed to the client when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message displayed to the client when the exception is thrown.","pos":[0,71]}]},{"pos":[11785,11871],"content":"The <xref:System.Exception.InnerException*>, if any, that threw the current exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Exception.InnerException*&gt;, if any, that threw the current exception.","pos":[0,86],"source":"The <xref:System.Exception.InnerException*>, if any, that threw the current exception."}]},{"pos":[12362,12493],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using an error message and an exception code.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an error message and an exception code."},{"pos":[13431,13502],"content":"The error message displayed to the client when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message displayed to the client when the exception is thrown.","pos":[0,71]}]},{"pos":[13560,13602],"content":"The exception code that defines the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception code that defines the error.","pos":[0,42]}]},{"pos":[14157,14354],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using an HTTP response status code, an error message, and the &lt;xref:System.Exception.InnerException*&gt; property.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an HTTP response status code, an error message, and the <xref:System.Exception.InnerException*> property."},{"pos":[14367,14949],"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.","needQuote":false,"needEscape":true,"extradata":"MT","nodes":[{"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.","pos":[0,580],"nodes":[{"content":"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.","pos":[0,157]},{"content":"A reference to the inner exception that caused the outer exception is available from the &lt;xref:System.Exception.InnerException%2A&gt; property of the outer exception.","pos":[164,327],"source":"       A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception."},{"content":"This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions.","pos":[328,511]},{"content":"For more information, see &lt;xref:System.Exception.InnerException%2A&gt;.","pos":[512,580],"source":" For more information, see <xref:System.Exception.InnerException%2A>."}]}]},{"pos":[16220,16274],"content":"The HTTP response status code displayed on the client.","needQuote":true,"needEscape":true,"nodes":[{"content":"The HTTP response status code displayed on the client.","pos":[0,54]}]},{"pos":[16338,16409],"content":"The error message displayed to the client when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message displayed to the client when the exception is thrown.","pos":[0,71]}]},{"pos":[16483,16569],"content":"The <xref:System.Exception.InnerException*>, if any, that threw the current exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Exception.InnerException*&gt;, if any, that threw the current exception.","pos":[0,86],"source":"The <xref:System.Exception.InnerException*>, if any, that threw the current exception."}]},{"pos":[17104,17266],"content":"Initializes a new instance of the <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> class using an HTTP response status code, an error message, and an exception code.","needQuote":true,"needEscape":true,"source":"Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an HTTP response status code, an error message, and an exception code."},{"pos":[18452,18506],"content":"The HTTP response status code displayed on the client.","needQuote":true,"needEscape":true,"nodes":[{"content":"The HTTP response status code displayed on the client.","pos":[0,54]}]},{"pos":[18570,18641],"content":"The error message displayed to the client when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message displayed to the client when the exception is thrown.","pos":[0,71]}]},{"pos":[18699,18741],"content":"The exception code that defines the error.","needQuote":true,"needEscape":true,"nodes":[{"content":"The exception code that defines the error.","pos":[0,42]}]},{"pos":[19227,19445],"content":"Creates a new <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> exception based on the error code that is returned from the Win32 API <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_GetLastError()\" name=\"GetLastError()\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> method.","needQuote":true,"needEscape":true,"source":"Creates a new <xref href=\"System.Web.HttpException\"></xref> exception based on the error code that is returned from the Win32 API <xref uid=\"langword_csharp_GetLastError()\" name=\"GetLastError()\" href=\"\"></xref> method."},{"pos":[19625,19696],"content":"The error message displayed to the client when the exception is thrown.","needQuote":true,"needEscape":true,"nodes":[{"content":"The error message displayed to the client when the exception is thrown.","pos":[0,71]}]},{"pos":[19765,19972],"content":"An <bpt id=\"p1\">&lt;xref href=\"System.Web.HttpException\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> based on the error code that is returned from a call to the Win32 API <bpt id=\"p2\">&lt;xref uid=\"langword_csharp_GetLastError()\" name=\"GetLastError()\" href=\"\"&gt;</bpt><ept id=\"p2\">&lt;/xref&gt;</ept> method.","needQuote":true,"needEscape":true,"source":"An <xref href=\"System.Web.HttpException\"></xref> based on the error code that is returned from a call to the Win32 API <xref uid=\"langword_csharp_GetLastError()\" name=\"GetLastError()\" href=\"\"></xref> method."},{"pos":[20424,20476],"content":"Gets the HTML error message to return to the client.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the HTML error message to return to the client.","pos":[0,52]}]},{"pos":[20614,20637],"content":"The HTML error message.","needQuote":true,"needEscape":true,"nodes":[{"content":"The HTML error message.","pos":[0,23]}]},{"pos":[21049,21108],"content":"Gets the HTTP response status code to return to the client.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the HTTP response status code to return to the client.","pos":[0,59]}]},{"pos":[21120,21618],"content":"If there is a non-zero HTTP code, it is returned. Otherwise, the <xref:System.Exception.InnerException%2A> code is returned. If neither an <xref:System.Exception.InnerException%2A> code nor a non-zero HTTP code is available, the HTTP response status code 500 is returned. For more information on HTTP response status codes, see the Status Code Definitions of the Hypertext Transfer Protocol - HTTP/1.1 on the World [Wide Web Consortium (W3C) Web site](http://go.microsoft.com/fwlink/?linkid=37125).","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"If there is a non-zero HTTP code, it is returned.","pos":[0,49]},{"content":"Otherwise, the &lt;xref:System.Exception.InnerException%2A&gt; code is returned.","pos":[50,124],"source":" Otherwise, the <xref:System.Exception.InnerException%2A> code is returned."},{"content":"If neither an &lt;xref:System.Exception.InnerException%2A&gt; code nor a non-zero HTTP code is available, the HTTP response status code 500 is returned.","pos":[125,271],"source":" If neither an <xref:System.Exception.InnerException%2A> code nor a non-zero HTTP code is available, the HTTP response status code 500 is returned."},{"content":"For more information on HTTP response status codes, see the Status Code Definitions of the Hypertext Transfer Protocol - HTTP/1.1 on the World <bpt id=\"p1\">[</bpt>Wide Web Consortium (W3C) Web site<ept id=\"p1\">](http://go.microsoft.com/fwlink/?linkid=37125)</ept>.","pos":[272,498],"source":" For more information on HTTP response status codes, see the Status Code Definitions of the Hypertext Transfer Protocol - HTTP/1.1 on the World [Wide Web Consortium (W3C) Web site](http://go.microsoft.com/fwlink/?linkid=37125)."}]},{"pos":[21744,21886],"content":"A non-zero HTTP code representing the exception or the <xref:System.Exception.InnerException*> code; otherwise, HTTP response status code 500.","needQuote":true,"needEscape":true,"nodes":[{"content":"A non-zero HTTP code representing the exception or the &lt;xref:System.Exception.InnerException*&gt; code; otherwise, HTTP response status code 500.","pos":[0,142],"source":"A non-zero HTTP code representing the exception or the <xref:System.Exception.InnerException*> code; otherwise, HTTP response status code 500."}]},{"pos":[22590,22721],"content":"Gets information about the exception and adds it to the <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> object.","needQuote":true,"needEscape":true,"source":"Gets information about the exception and adds it to the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object."},{"pos":[22733,23053],"content":"The GetObjectData method adds information about the exception to the <xref:System.Runtime.Serialization.SerializationInfo> object that is targeted for serialization. During deserialization, the exception is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> that is transmitted over the stream.","needQuote":true,"needEscape":true,"extradata":"MT","nodes":[{"content":"The GetObjectData method adds information about the exception to the <xref:System.Runtime.Serialization.SerializationInfo> object that is targeted for serialization. During deserialization, the exception is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> that is transmitted over the stream.","pos":[0,320],"nodes":[{"content":"The GetObjectData method adds information about the exception to the &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; object that is targeted for serialization.","pos":[0,165],"source":"The GetObjectData method adds information about the exception to the <xref:System.Runtime.Serialization.SerializationInfo> object that is targeted for serialization."},{"content":"During deserialization, the exception is reconstituted from the &lt;xref:System.Runtime.Serialization.SerializationInfo&gt; that is transmitted over the stream.","pos":[166,320],"source":" During deserialization, the exception is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> that is transmitted over the stream."}]}]},{"pos":[23331,23474],"content":"The <bpt id=\"p1\">&lt;xref href=\"System.Runtime.Serialization.SerializationInfo\"&gt;</bpt><ept id=\"p1\">&lt;/xref&gt;</ept> that holds the serialized object data about the exception being thrown.","needQuote":true,"needEscape":true,"source":"The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown."},{"pos":[23570,23697],"content":"The <xref:System.Runtime.Serialization.StreamingContext> that holds the contextual information about the source or destination.","needQuote":true,"needEscape":true,"nodes":[{"content":"The &lt;xref:System.Runtime.Serialization.StreamingContext&gt; that holds the contextual information about the source or destination.","pos":[0,127],"source":"The <xref:System.Runtime.Serialization.StreamingContext> that holds the contextual information about the source or destination."}]},{"pos":[24104,24169],"content":"Gets the event codes that are associated with the HTTP exception.","needQuote":true,"needEscape":true,"nodes":[{"content":"Gets the event codes that are associated with the HTTP exception.","pos":[0,65]}]},{"pos":[24282,24323],"content":"An integer representing a Web event code.","needQuote":true,"needEscape":true,"nodes":[{"content":"An integer representing a Web event code.","pos":[0,41]}]}],"content":"### YamlMime:ManagedReference\nitems:\n- uid: System.Web.HttpException\n  id: HttpException\n  children:\n  - System.Web.HttpException.#ctor\n  - System.Web.HttpException.#ctor(System.String)\n  - System.Web.HttpException.#ctor(System.Int32,System.String)\n  - System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Web.HttpException.#ctor(System.String,System.Exception)\n  - System.Web.HttpException.#ctor(System.String,System.Int32)\n  - System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)\n  - System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)\n  - System.Web.HttpException.CreateFromLastError(System.String)\n  - System.Web.HttpException.GetHtmlErrorMessage\n  - System.Web.HttpException.GetHttpCode\n  - System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  - System.Web.HttpException.WebEventCode\n  langs:\n  - csharp\n  name: HttpException\n  nameWithType: HttpException\n  fullName: System.Web.HttpException\n  type: Class\n  summary: Describes an exception that occurred during the processing of HTTP requests.\n  remarks: The HttpException class is an HTTP-specific exception class that enables ASP.NET to generate exception information. For more information about throwing and handling exceptions, see [Exceptions](~/add/includes/ajax-current-ext-md.md).\n  example:\n  - \"The following code example demonstrates how to use the HttpException class to raise customized exceptions. The `Button_Click` method determines which button was clicked, and then calls either the `CheckNumber` or `CheckBoolean` method. If the user-entered value in the text box does not correspond to the expected type, an HttpException exception is created and thrown with a customized message based on the error type.  \\n  \\n> [!IMPORTANT]\\n>  This example has a text box that accepts user input, which is a potential security threat. By default, ASP.NET Web pages validate that user input does not include script or HTML elements. For more information, see [Script Exploits Overview](~/add/includes/ajax-current-ext-md.md).  \\n  \\n [!code-vb[HttpException#1](~/add/codesnippet/visualbasic/t-system.web.httpexception_1.aspx)]\\n [!code-cs[HttpException#1](~/add/codesnippet/csharp/t-system.web.httpexception_1.aspx)]\"\n  syntax:\n    content: 'public class HttpException : System.Runtime.InteropServices.ExternalException'\n  inheritance:\n  - System.Exception\n  - System.SystemException\n  - System.Runtime.InteropServices.ExternalException\n  implements: []\n  inheritedMembers:\n  - System.Runtime.InteropServices.ExternalException.ErrorCode\n  - System.Runtime.InteropServices.ExternalException.ToString\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor\n  id: '#ctor'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException()\n  nameWithType: HttpException.HttpException()\n  fullName: System.Web.HttpException.HttpException()\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class and creates an empty <xref href=\"System.Web.HttpException\"></xref> object.\n  remarks: \"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.  \\n  \\n A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.\"\n  example:\n  - \"The following code example demonstrates the HttpException constructor of the <xref:System.Web.HttpException> class. The `CheckNumber` method accepts a user-entered value through a text box and checks whether it is an integer. If the value is not an integer, an exception is thrown, and then a new <xref:System.Web.HttpException> object is created and thrown. That exception is caught in the `Button_Click` event handler and the error message is displayed on the browser.  \\n  \\n> [!IMPORTANT]\\n>  This example has a text box that accepts user input, which is a potential security threat. By default, ASP.NET Web pages validate that user input does not include script or HTML elements. For more information, see [Script Exploits Overview](~/add/includes/ajax-current-ext-md.md).  \\n  \\n [!code-cs[HttpException_Constructor1#1](~/add/codesnippet/csharp/m-system.web.httpexcepti_2_1.aspx)]\\n [!code-vb[HttpException_Constructor1#1](~/add/codesnippet/visualbasic/m-system.web.httpexcepti_2_1.aspx)]\"\n  syntax:\n    content: public HttpException ();\n    parameters: []\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor(System.String)\n  id: '#ctor(System.String)'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException(String)\n  nameWithType: HttpException.HttpException(String)\n  fullName: System.Web.HttpException.HttpException(String)\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using a supplied error message.\n  remarks: ''\n  example:\n  - \"The following code example demonstrates the HttpException constructor of the <xref:System.Web.HttpException> class. An <xref:System.Web.HttpException> is thrown if a user-entered value is 0.  \\n  \\n> [!IMPORTANT]\\n>  This example has a text box that accepts user input, which is a potential security threat. By default, ASP.NET Web pages validate that user input does not include script or HTML elements. For more information, see [Script Exploits Overview](~/add/includes/ajax-current-ext-md.md).  \\n  \\n [!code-cs[Classic HttpException.HttpException1 Example#1](~/add/codesnippet/csharp/m-system.web.httpexcepti_0_1.cs)]\\n [!code-vb[Classic HttpException.HttpException1 Example#1](~/add/codesnippet/visualbasic/m-system.web.httpexcepti_0_1.vb)]\"\n  syntax:\n    content: public HttpException (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message displayed to the client when the exception is thrown.\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor(System.Int32,System.String)\n  id: '#ctor(System.Int32,System.String)'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException(Int32,String)\n  nameWithType: HttpException.HttpException(Int32,String)\n  fullName: System.Web.HttpException.HttpException(Int32,String)\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an HTTP response status code and an error message.\n  syntax:\n    content: public HttpException (int httpCode, string message);\n    parameters:\n    - id: httpCode\n      type: System.Int32\n      description: The HTTP response status code sent to the client corresponding to this error.\n    - id: message\n      type: System.String\n      description: The error message displayed to the client when the exception is thrown.\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException(SerializationInfo,StreamingContext)\n  nameWithType: HttpException.HttpException(SerializationInfo,StreamingContext)\n  fullName: System.Web.HttpException.HttpException(SerializationInfo,StreamingContext)\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class with serialized data.\n  remarks: The HttpException constructor is called during deserialization to reconstitute the exception object that is transmitted over a stream. For more information, see [XML and SOAP Serialization](~/add/includes/ajax-current-ext-md.md).\n  syntax:\n    content: protected HttpException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The <xref:System.Runtime.Serialization.StreamingContext> that holds the contextual information about the source or destination.\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor(System.String,System.Exception)\n  id: '#ctor(System.String,System.Exception)'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException(String,Exception)\n  nameWithType: HttpException.HttpException(String,Exception)\n  fullName: System.Web.HttpException.HttpException(String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an error message and the <xref:System.Exception.InnerException*> property.\n  remarks: \"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.  \\n  \\n A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.\"\n  example:\n  - \"The following code example demonstrates the HttpException constructor of the <xref:System.Web.HttpException> class. The `CheckNumber` method accepts a user-entered value through a text box and checks whether it is an integer. If the value is not an integer, an exception is thrown, and then in the catch block, a new <xref:System.Web.HttpException> object is created and thrown. That exception is caught in the `Button_Click` event handler and the error message is displayed on the browser.  \\n  \\n> [!IMPORTANT]\\n>  This example has a text box that accepts user input, which is a potential security threat. By default, ASP.NET Web pages validate that user input does not include script or HTML elements. For more information, see [Script Exploits Overview](~/add/includes/ajax-current-ext-md.md).  \\n  \\n [!code-vb[HttpException_Constructor2#1](~/add/codesnippet/visualbasic/m-system.web.httpexcepti_1_1.aspx)]\\n [!code-cs[HttpException_Constructor2#1](~/add/codesnippet/csharp/m-system.web.httpexcepti_1_1.aspx)]\"\n  syntax:\n    content: public HttpException (string message, Exception innerException);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message displayed to the client when the exception is thrown.\n    - id: innerException\n      type: System.Exception\n      description: The <xref:System.Exception.InnerException*>, if any, that threw the current exception.\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor(System.String,System.Int32)\n  id: '#ctor(System.String,System.Int32)'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException(String,Int32)\n  nameWithType: HttpException.HttpException(String,Int32)\n  fullName: System.Web.HttpException.HttpException(String,Int32)\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an error message and an exception code.\n  remarks: ''\n  example:\n  - \"The following code example demonstrates the HttpException constructor of the <xref:System.Web.HttpException> class. An <xref:System.Web.HttpException> exception is thrown if a user-entered value is 0.  \\n  \\n> [!IMPORTANT]\\n>  This example has a text box that accepts user input, which is a potential security threat. By default, ASP.NET Web pages validate that user input does not include script or HTML elements. For more information, see [Script Exploits Overview](~/add/includes/ajax-current-ext-md.md).  \\n  \\n [!code-vb[Classic HttpException.HttpException2 Example#1](~/add/codesnippet/visualbasic/m-system.web.httpexcepti_4_1.vb)]\\n [!code-cs[Classic HttpException.HttpException2 Example#1](~/add/codesnippet/csharp/m-system.web.httpexcepti_4_1.cs)]\"\n  syntax:\n    content: public HttpException (string message, int hr);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message displayed to the client when the exception is thrown.\n    - id: hr\n      type: System.Int32\n      description: The exception code that defines the error.\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)\n  id: '#ctor(System.Int32,System.String,System.Exception)'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException(Int32,String,Exception)\n  nameWithType: HttpException.HttpException(Int32,String,Exception)\n  fullName: System.Web.HttpException.HttpException(Int32,String,Exception)\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an HTTP response status code, an error message, and the <xref:System.Exception.InnerException*> property.\n  remarks: \"When handling exceptions, it can be useful to capture a series of related exceptions with the outer exception being thrown in response to an inner exception.  \\n  \\n A reference to the inner exception that caused the outer exception is available from the <xref:System.Exception.InnerException%2A> property of the outer exception. This mechanism preserves the error information that is carried by earlier exceptions, including the original exceptions, while allowing you to create more meaningful outer exceptions. For more information, see <xref:System.Exception.InnerException%2A>.\"\n  example:\n  - \"The following code example demonstrates the HttpException constructor of the <xref:System.Web.HttpException> class. The `CheckNumber` method accepts a user-entered value and checks whether it is an integer. If the value is not an integer, an exception is thrown, and then a new <xref:System.Web.HttpException> object containing the HTTP response status code, the exception's message, and any inner exception is created. That exception is caught in the `Button_Click` event handler and the error message, error code, and inner exception are displayed.  \\n  \\n> [!IMPORTANT]\\n>  This example has a text box that accepts user input, which is a potential security threat. By default, ASP.NET Web pages validate that user input does not include script or HTML elements. For more information, see [Script Exploits Overview](~/add/includes/ajax-current-ext-md.md).  \\n  \\n [!code-cs[HttpException_Constructor3#1](~/add/codesnippet/csharp/6bc30991-e249-4e7f-addb-_1.aspx)]\\n [!code-vb[HttpException_Constructor3#1](~/add/codesnippet/visualbasic/6bc30991-e249-4e7f-addb-_1.aspx)]\"\n  syntax:\n    content: public HttpException (int httpCode, string message, Exception innerException);\n    parameters:\n    - id: httpCode\n      type: System.Int32\n      description: The HTTP response status code displayed on the client.\n    - id: message\n      type: System.String\n      description: The error message displayed to the client when the exception is thrown.\n    - id: innerException\n      type: System.Exception\n      description: The <xref:System.Exception.InnerException*>, if any, that threw the current exception.\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)\n  id: '#ctor(System.Int32,System.String,System.Int32)'\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: HttpException(Int32,String,Int32)\n  nameWithType: HttpException.HttpException(Int32,String,Int32)\n  fullName: System.Web.HttpException.HttpException(Int32,String,Int32)\n  type: Constructor\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Initializes a new instance of the <xref href=\"System.Web.HttpException\"></xref> class using an HTTP response status code, an error message, and an exception code.\n  remarks: ''\n  example:\n  - \"The following code example demonstrates the HttpException constructor of the <xref:System.Web.HttpException> class. The user name and e-mail information are entered by the user in the provided text boxes. If any of the text boxes are left blank, an <xref:System.Web.HttpException> object is created and thrown. The error code of the <xref:System.Web.HttpException> is obtained by the <xref:System.Web.HttpException.GetHttpCode%2A> method and displayed on the Web page.  \\n  \\n> [!IMPORTANT]\\n>  This example has a text box that accepts user input, which is a potential security threat. By default, ASP.NET Web pages validate that user input does not include script or HTML elements. For more information, see [Script Exploits Overview](~/add/includes/ajax-current-ext-md.md).  \\n  \\n [!code-cs[HttpException_Constructor#1](~/add/codesnippet/csharp/m-system.web.httpexcepti_3_1.aspx)]\\n [!code-vb[HttpException_Constructor#1](~/add/codesnippet/visualbasic/m-system.web.httpexcepti_3_1.aspx)]\"\n  syntax:\n    content: public HttpException (int httpCode, string message, int hr);\n    parameters:\n    - id: httpCode\n      type: System.Int32\n      description: The HTTP response status code displayed on the client.\n    - id: message\n      type: System.String\n      description: The error message displayed to the client when the exception is thrown.\n    - id: hr\n      type: System.Int32\n      description: The exception code that defines the error.\n  overload: System.Web.HttpException.#ctor*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.CreateFromLastError(System.String)\n  id: CreateFromLastError(System.String)\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: CreateFromLastError(String)\n  nameWithType: HttpException.CreateFromLastError(String)\n  fullName: System.Web.HttpException.CreateFromLastError(String)\n  type: Method\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Creates a new <xref href=\"System.Web.HttpException\"></xref> exception based on the error code that is returned from the Win32 API <xref uid=\"langword_csharp_GetLastError()\" name=\"GetLastError()\" href=\"\"></xref> method.\n  syntax:\n    content: public static System.Web.HttpException CreateFromLastError (string message);\n    parameters:\n    - id: message\n      type: System.String\n      description: The error message displayed to the client when the exception is thrown.\n    return:\n      type: System.Web.HttpException\n      description: An <xref href=\"System.Web.HttpException\"></xref> based on the error code that is returned from a call to the Win32 API <xref uid=\"langword_csharp_GetLastError()\" name=\"GetLastError()\" href=\"\"></xref> method.\n  overload: System.Web.HttpException.CreateFromLastError*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.GetHtmlErrorMessage\n  id: GetHtmlErrorMessage\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: GetHtmlErrorMessage()\n  nameWithType: HttpException.GetHtmlErrorMessage()\n  fullName: System.Web.HttpException.GetHtmlErrorMessage()\n  type: Method\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Gets the HTML error message to return to the client.\n  syntax:\n    content: public string GetHtmlErrorMessage ();\n    parameters: []\n    return:\n      type: System.String\n      description: The HTML error message.\n  overload: System.Web.HttpException.GetHtmlErrorMessage*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.GetHttpCode\n  id: GetHttpCode\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: GetHttpCode()\n  nameWithType: HttpException.GetHttpCode()\n  fullName: System.Web.HttpException.GetHttpCode()\n  type: Method\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Gets the HTTP response status code to return to the client.\n  remarks: If there is a non-zero HTTP code, it is returned. Otherwise, the <xref:System.Exception.InnerException%2A> code is returned. If neither an <xref:System.Exception.InnerException%2A> code nor a non-zero HTTP code is available, the HTTP response status code 500 is returned. For more information on HTTP response status codes, see the Status Code Definitions of the Hypertext Transfer Protocol - HTTP/1.1 on the World [Wide Web Consortium (W3C) Web site](http://go.microsoft.com/fwlink/?linkid=37125).\n  syntax:\n    content: public int GetHttpCode ();\n    parameters: []\n    return:\n      type: System.Int32\n      description: A non-zero HTTP code representing the exception or the <xref:System.Exception.InnerException*> code; otherwise, HTTP response status code 500.\n  overload: System.Web.HttpException.GetHttpCode*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: GetObjectData(SerializationInfo,StreamingContext)\n  nameWithType: HttpException.GetObjectData(SerializationInfo,StreamingContext)\n  fullName: System.Web.HttpException.GetObjectData(SerializationInfo,StreamingContext)\n  type: Method\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Gets information about the exception and adds it to the <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> object.\n  remarks: The GetObjectData method adds information about the exception to the <xref:System.Runtime.Serialization.SerializationInfo> object that is targeted for serialization. During deserialization, the exception is reconstituted from the <xref:System.Runtime.Serialization.SerializationInfo> that is transmitted over the stream.\n  syntax:\n    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);\n    parameters:\n    - id: info\n      type: System.Runtime.Serialization.SerializationInfo\n      description: The <xref href=\"System.Runtime.Serialization.SerializationInfo\"></xref> that holds the serialized object data about the exception being thrown.\n    - id: context\n      type: System.Runtime.Serialization.StreamingContext\n      description: The <xref:System.Runtime.Serialization.StreamingContext> that holds the contextual information about the source or destination.\n  overload: System.Web.HttpException.GetObjectData*\n  exceptions: []\n  platform:\n  - net462\n- uid: System.Web.HttpException.WebEventCode\n  id: WebEventCode\n  parent: System.Web.HttpException\n  langs:\n  - csharp\n  name: WebEventCode\n  nameWithType: HttpException.WebEventCode\n  fullName: System.Web.HttpException.WebEventCode\n  type: Property\n  assemblies:\n  - System.Web\n  namespace: System.Web\n  summary: Gets the event codes that are associated with the HTTP exception.\n  syntax:\n    content: public int WebEventCode { get; }\n    return:\n      type: System.Int32\n      description: An integer representing a Web event code.\n  overload: System.Web.HttpException.WebEventCode*\n  exceptions: []\n  platform:\n  - net462\nreferences:\n- uid: System.Runtime.InteropServices.ExternalException\n  isExternal: false\n  name: System.Runtime.InteropServices.ExternalException\n- uid: System.Web.HttpException.#ctor\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException()\n  nameWithType: HttpException.HttpException()\n  fullName: System.Web.HttpException.HttpException()\n- uid: System.Web.HttpException.#ctor(System.String)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException(String)\n  nameWithType: HttpException.HttpException(String)\n  fullName: System.Web.HttpException.HttpException(String)\n- uid: System.String\n  parent: System\n  isExternal: true\n  name: String\n  nameWithType: String\n  fullName: System.String\n- uid: System.Web.HttpException.#ctor(System.Int32,System.String)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException(Int32,String)\n  nameWithType: HttpException.HttpException(Int32,String)\n  fullName: System.Web.HttpException.HttpException(Int32,String)\n- uid: System.Int32\n  parent: System\n  isExternal: true\n  name: Int32\n  nameWithType: Int32\n  fullName: System.Int32\n- uid: System.Web.HttpException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException(SerializationInfo,StreamingContext)\n  nameWithType: HttpException.HttpException(SerializationInfo,StreamingContext)\n  fullName: System.Web.HttpException.HttpException(SerializationInfo,StreamingContext)\n- uid: System.Runtime.Serialization.SerializationInfo\n  parent: System.Runtime.Serialization\n  isExternal: false\n  name: SerializationInfo\n  nameWithType: SerializationInfo\n  fullName: System.Runtime.Serialization.SerializationInfo\n- uid: System.Runtime.Serialization.StreamingContext\n  parent: System.Runtime.Serialization\n  isExternal: true\n  name: StreamingContext\n  nameWithType: StreamingContext\n  fullName: System.Runtime.Serialization.StreamingContext\n- uid: System.Web.HttpException.#ctor(System.String,System.Exception)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException(String,Exception)\n  nameWithType: HttpException.HttpException(String,Exception)\n  fullName: System.Web.HttpException.HttpException(String,Exception)\n- uid: System.Exception\n  parent: System\n  isExternal: true\n  name: Exception\n  nameWithType: Exception\n  fullName: System.Exception\n- uid: System.Web.HttpException.#ctor(System.String,System.Int32)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException(String,Int32)\n  nameWithType: HttpException.HttpException(String,Int32)\n  fullName: System.Web.HttpException.HttpException(String,Int32)\n- uid: System.Web.HttpException.#ctor(System.Int32,System.String,System.Exception)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException(Int32,String,Exception)\n  nameWithType: HttpException.HttpException(Int32,String,Exception)\n  fullName: System.Web.HttpException.HttpException(Int32,String,Exception)\n- uid: System.Web.HttpException.#ctor(System.Int32,System.String,System.Int32)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException(Int32,String,Int32)\n  nameWithType: HttpException.HttpException(Int32,String,Int32)\n  fullName: System.Web.HttpException.HttpException(Int32,String,Int32)\n- uid: System.Web.HttpException.CreateFromLastError(System.String)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: CreateFromLastError(String)\n  nameWithType: HttpException.CreateFromLastError(String)\n  fullName: System.Web.HttpException.CreateFromLastError(String)\n- uid: System.Web.HttpException\n  parent: System.Web\n  isExternal: false\n  name: HttpException\n  nameWithType: HttpException\n  fullName: System.Web.HttpException\n- uid: System.Web.HttpException.GetHtmlErrorMessage\n  parent: System.Web.HttpException\n  isExternal: false\n  name: GetHtmlErrorMessage()\n  nameWithType: HttpException.GetHtmlErrorMessage()\n  fullName: System.Web.HttpException.GetHtmlErrorMessage()\n- uid: System.Web.HttpException.GetHttpCode\n  parent: System.Web.HttpException\n  isExternal: false\n  name: GetHttpCode()\n  nameWithType: HttpException.GetHttpCode()\n  fullName: System.Web.HttpException.GetHttpCode()\n- uid: System.Web.HttpException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)\n  parent: System.Web.HttpException\n  isExternal: false\n  name: GetObjectData(SerializationInfo,StreamingContext)\n  nameWithType: HttpException.GetObjectData(SerializationInfo,StreamingContext)\n  fullName: System.Web.HttpException.GetObjectData(SerializationInfo,StreamingContext)\n- uid: System.Web.HttpException.WebEventCode\n  parent: System.Web.HttpException\n  isExternal: false\n  name: WebEventCode\n  nameWithType: HttpException.WebEventCode\n  fullName: System.Web.HttpException.WebEventCode\n- uid: System.Web.HttpException.#ctor*\n  parent: System.Web.HttpException\n  isExternal: false\n  name: HttpException\n  nameWithType: HttpException.HttpException\n- uid: System.Web.HttpException.CreateFromLastError*\n  parent: System.Web.HttpException\n  isExternal: false\n  name: CreateFromLastError\n  nameWithType: HttpException.CreateFromLastError\n- uid: System.Web.HttpException.GetHtmlErrorMessage*\n  parent: System.Web.HttpException\n  isExternal: false\n  name: GetHtmlErrorMessage\n  nameWithType: HttpException.GetHtmlErrorMessage\n- uid: System.Web.HttpException.GetHttpCode*\n  parent: System.Web.HttpException\n  isExternal: false\n  name: GetHttpCode\n  nameWithType: HttpException.GetHttpCode\n- uid: System.Web.HttpException.GetObjectData*\n  parent: System.Web.HttpException\n  isExternal: false\n  name: GetObjectData\n  nameWithType: HttpException.GetObjectData\n- uid: System.Web.HttpException.WebEventCode*\n  parent: System.Web.HttpException\n  isExternal: false\n  name: WebEventCode\n  nameWithType: HttpException.WebEventCode\n"}